Projeto Final/Site-com-Python-main/Projeto_modesto/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from website.models import User
from .models import Paciente
from .models import Atendimento
from . import db
from flask_login import login_user, login_required,logout_user, current_user


auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET','POST'])#permitir que o sistema receba as informações
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        senha = request.form.get('senha')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.senha, senha):
                flash('Logado com sucesso!', category='sucedida')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Senha incorreta, tente novamente!', category='erro')
        else:
            flash('Email inexistente.', category='erro')
                                     

    return render_template("login.html", user= current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET','POST'])#permitir que o sistema receba as informações
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        nome = request.form.get('nome')
        sobrenome = request.form.get('sobrenome')
        crm = request.form.get('crm')
        data = request.form.get('data')
        senha = request.form.get('senha')
        senha2 = request.form.get('senha2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Este email já existe.', category = 'erro')
        elif len(email)< 11:
            flash('O email deve ser maior que 10 caracteres', category='erro')
        elif len(nome)< 3:
            flash('O nome deve ser maior que 2 caracteres', category='erro')
        elif len(sobrenome)< 2:
            flash('O sobrenome deve ser maior que 1 caracter', category='erro')
        elif senha != senha2:
            flash('As senhas não são iguais', category='erro')
        elif len(senha)< 7:
            flash('A senha deve ser maior que 6 caracteres', category='erro')
        else:
            #adicionar o usuário no banco de dados
            new_user = User(email=email, nome=nome, senha=generate_password_hash(senha, method='pbkdf2:sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Conta criada com sucesso!', category='sucedida')
            return redirect(url_for('views.home'))
        
    return render_template("sign_up.html", user = current_user)

@auth.route('/paciente', methods=['GET','POST'])#permitir que o sistema receba as informações
@login_required
def paciente():
    if request.method == 'POST':
        nome = request.form.get('nome')
        CPF = request.form.get('CPF')
        temcpf = Paciente.query.filter_by(cpf=CPF).first()
        if temcpf:
            flash('CPF já cadastrado.', category='erro')
        else:
            idade = request.form.get('idade')
            
            novo_paciente = Paciente(cpf=CPF, nome=nome, idade=idade)
            db.session.add(novo_paciente)
            db.session.commit()

            flash("Cadastro de paciente criado com sucesso!", category = 'sucedida')
        
      

    return render_template("paciente.html", user=current_user)

@auth.route('/atendimento', methods=['GET', 'POST'])
@login_required
def atendimento():

    paciente = None 
    if request.method == 'POST':
        cpf = request.form.get('CPF')

        paciente = Paciente.query.filter_by(cpf=cpf).first()

        if paciente:
            temperatura = float(request.form.get('temperatura'))
            pressao = float(request.form.get('pressao'))
            dores = request.form.get('dores')
            perda_consciencia = request.form.get('perda_consciencia')
            dificuldade_respiratoria = request.form.get('dificuldade_respiratoria')

            urgencia = 0

            if temperatura > 38.0 or temperatura < 35.0:
                urgencia += 1

            if pressao > 140 or pressao < 90:
                urgencia += 1

            if perda_consciencia == '2':
                urgencia += 2

            elif perda_consciencia == '1':
                urgencia += 1

            if dificuldade_respiratoria == '2':
                urgencia += 2
            
            elif dificuldade_respiratoria == '1':
                urgencia += 1

            if dores == '1':
                urgencia += 2

            elif dores == '2':
                urgencia += 1

            novo_atendimento = Atendimento(temperatura=temperatura,  pressao =pressao, dores=dores, perda_consciencia=perda_consciencia, dificuldade_respiratoria=dificuldade_respiratoria,urgencia=urgencia, paciente_id=paciente.id)
            db.session.add(novo_atendimento)
            db.session.commit()

            flash("Adicionado!", category = 'sucedida')
            return render_template("atendimento.html", user=current_user, paciente=paciente)
        else:
            flash("Paciente não encontrado. Por favor, cadastre o paciente", category = 'erro')
    
    return render_template('atendimento.html', user=current_user, paciente=paciente)

@auth.route('/detalhes_paciente/<int:paciente_id>')
@login_required
def detalhes_paciente(paciente_id):
    paciente = Paciente.query.get(paciente_id)
    atendimentos = Atendimento.query.filter_by(paciente_id=paciente_id).all()
    return render_template('detalhes_paciente.html', user=current_user, paciente=paciente, atendimentos=atendimentos)

Projeto Final/Site-com-Python-main/Projeto_modesto/website/views.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user
from .models import Paciente, Atendimento
from . import db
from sqlalchemy import desc

views = Blueprint('views', __name__)
#colocando urls nas nossas pages

@views.route('/')
@login_required
def home():
    pacientes = (
        db.session.query(Paciente, Atendimento)
        .join(Atendimento, Paciente.id == Atendimento.paciente_id)
        .order_by(desc(Atendimento.urgencia))
        .all()
    )
    
    return render_template("home.html", user=current_user, pacientes=pacientes)

@views.route('/marcar_atendido/<int:atendimento_id>', methods=['GET', 'POST'])
@login_required
def marcar_atendido(atendimento_id):
    atendimento = Atendimento.query.get(atendimento_id)
    if atendimento:
       atendimento.atendido = True
       db.session.commit()
    return redirect(url_for('views.home'))

Projeto Final/Site-com-Python-main/Projeto_modesto/website/templates/atendimento.html
{% extends "base.html" %} {% block title %}Triagem Médica{% endblock %}

{% block conteudo %}
<form method="POST">
    <br/>
    <h3 align="center">Ficha de atendimento</h3>
    <div class="form-group">
        <label for="CPF">CPF</label>
        <input 
            type="text" 
            class="form-control" 
            id="CPF" 
            name="CPF" 
            placeholder="000.000.000-00"
            >
    </div>
    <div class="form-group">
        <label for="temperatura">Temperatura em C°</label>
        <input 
            type="number" 
            class="form-control" 
            id="temperatura" 
            name="temperatura" 
            placeholder="Digite a temperatura"
            >
    </div>
    <div class="form-group">
        <label for="pressao">Pressão</label>
        <input 
            type="number" 
            class="form-control" 
            id="pressao" 
            name="pressao" 
            placeholder="Digite a a pressão"
            >
    </div>

    <label for="dores">Nível de Dor:</label> 
    <select id="dores" name="dores">
        <option value="0">Sem dor</option>
        <option value="1">Leve</option>
        <option value="2">Grave</option>
    </select>
    <br/>
    <label for="perda_consciencia">Perda de Consciência:</label> 
    <select id="perda_consciencia" name="perda_consciencia">
        <option value="0">Não tem</option>
        <option value="1">Leve</option>
        <option value="2">Grave</option>
    </select>
    <br/>
    <label for="dificuldade_respiratoria">Dificuldade Respiratória:</label> 
    <select id="dificuldade_respiratoria" name="dificuldade_respiratoria">
        <option value="0">Não tem</option>
        <option value="1">Leve</option>
        <option value="2">Grave</option>
    </select>
    <br/>
    <br/>
    <button 
    type="submit"
    class="btn btn-primary">Cadastre</button>
    </form>
{% endblock %}

Projeto Final/Site-com-Python-main/Projeto_modesto/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

     <!--Normalize Css-->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!--Fonte Roboto-->
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500;700&display=swap" rel="stylesheet"/>

    <!--framework de css para costumizar o site--> 
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <!-- css pasta -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}"/>
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button 
        class="navbar-toggler" 
        type="button" 
        data-toggle="collapse" 
        data-target="#navbar"
        >
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav">
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" id="home" href="/">Urgências</a>
            <a class="nav-item nav-link" id="paciente" href="/paciente">Cadastrar Pacientes</a>
            <a class="nav-item nav-link" id="atendimento" href="/atendimento">Atendimento</a>
            <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
            {% else %}
            <a class="nav-item nav-link" id="login" href="/login">Login</a>
            <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
            {% endif %}
          </div>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages%}
      {% if category == 'erro' %}
      <div class = "alert alert-danger alter-dismissable fade show" role ="alert">
          {{ message }}
          <button type ="button" class = "close" data-dismiss = "alert">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
      {% else %}
      <div class = "alert alert-success alter-dismissable fade show" role ="alert">
        {{ message }}
        <button type ="button" class = "close" data-dismiss = "alert">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}

    <div class="container">
      {% block conteudo %}
      {% endblock %}
    </div>
  
      <script
          src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
          integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
          integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
          integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
          crossorigin="anonymous"
        ></script>
  </body>
</html>

Projeto Final/Site-com-Python-main/Projeto_modesto/website/templates/detalhes_paciente.html
{% extends "base.html" %} 
{% block title %}Detalhes do Paciente{% endblock %}

{% block conteudo %}
  
    <h2>Detalhes do Paciente:</h2>
    <p>Nome: {{ paciente.nome }}</p>
    <p>Idade: {{ paciente.idade }}</p>
    <br/>

    {% for atendimento in atendimentos %}
      <p>{{ atendimento.data_atendimento }}</p>
      <p>Temperatura: {{ atendimento.temperatura }}</p>
      <p>Pressão: {{ atendimento.pressao }}</p>

      {% if atendimento.dores == 0 %}
        <p>Dores: Não</p>      
      {% elif atendimento.dores == 1 %}
        <p>Dores: Leve</p> 
      {% else %}
        <p>Dores: Grave</p> 
      {% endif %}

      {% if atendimento.perda_consciencia == 0 %}
        <p>Perda de Consciência: Não</p>      
      {% elif atendimento.perda_consciencia == 1 %}
        <p>Perda de Consciência: Leve</p> 
      {% else %}
        <p>Perda de Consciência: Grave</p> 
      {% endif %}

      {% if atendimento.dificuldade_respiratoria == 0 %}
        <p>Dificuldade Respiratória: Não</p>      
      {% elif atendimento.dificuldade_respiratoria == 1 %}
        <p>Dificuldade Respiratória: Leve</p> 
      {% else %}
        <p>Dificuldade Respiratória: Grave</p> 
      {% endif %}

      {% if not atendimento.atendido %}
        <form action="{{ url_for('views.marcar_atendido', atendimento_id=atendimento.id) }}" method="post" style="display: inline;">
          <button type="submit" class="btn btn-success btn-sm">Atendido</button>
        </form>
      {% endif %}
      <br/>
  {% endfor %}
{% endblock %}

Projeto Final/Site-com-Python-main/Projeto_modesto/website/templates/home.html
{% extends "base.html" %}

{% block title %}
  Triagem Médica
{% endblock %}

{% block conteudo %}
  <h2>Urgências:</h2>
  <ul>
    {% for paciente, atendimento in pacientes %}
      {% if not atendimento.atendido %}
        <li>
          <p><a href="{{ url_for('auth.detalhes_paciente', paciente_id=paciente.id) }}">{{ paciente.nome }}</a></p>
        </li>
      {% endif %}
    {% endfor %}
  </ul>
{% endblock %}

Projeto Final/Site-com-Python-main/Projeto_modesto/website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %}

{% block conteudo %}

<head>
</head>

<form method="POST">
    <section class="login">
    <h3 align="center">Cadastro de Médicos</h3>
    <div class="form-group">
        <label for="email">Email</label>
        <input 
            type="email" 
            class="form-control" 
            id="email" 
            name="email" 
            placeholder="Digite seu email"
            >
    </div>
    <div class="form-group">
        <label for="senha">Senha</label>
        <input 
            type="password" 
            class="form-control" 
            id="senha" 
            name="senha" 
            placeholder="Senha"
            >
    </div>
    <button 
    type="submit"
    class="btn btn-primary">Login</button>
</section>
    </form>
{% endblock %}


Projeto Final/Site-com-Python-main/Projeto_modesto/website/templates/paciente.html
{% extends "base.html" %} {% block title %}Triagem Médica{% endblock %}

{% block conteudo %}
<form method="POST">
    <br/>
    <h3 align="center">Cadastro de Pacientes</h3>
    <div class="form-group">
        <label for="nome">Nome</label>
        <input 
            type="text" 
            class="form-control" 
            id="nome" 
            name="nome" 
            placeholder="Nome Completo"
            >
    </div>
    <div class="form-group">
        <label for="CPF">CPF</label>
        <input 
            type="text" 
            class="form-control" 
            id="CPF" 
            name="CPF" 
            placeholder="000.000.000-00"
            >
    </div>
    <div class="form-group">
        <label for="idade">Idade</label>
        <input 
            type="number" 
            class="form-control" 
            id="idade" 
            name="idade" 
            placeholder="Digite a idade"
            >
    </div>
    <br/>
    <button 
    type="submit"
    class="btn btn-primary">Cadastre</button>
    </form>
{% endblock %}

Projeto Final/Site-com-Python-main/Projeto_modesto/website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Cadastro Triagem Médica{% endblock %}

{% block conteudo %}
<form method="POST">
    <h3 align="center">Cadastro de Médicos</h3>
    <div class="form-group">
        <label for="email">Email</label>
        <input 
            type="email" 
            class="form-control" 
            id="email" 
            name="email" 
            placeholder="Digite seu email"
            >
    </div>
    <div class="form-group">
        <label for="nome">Nome</label>
        <input 
            type="text" 
            class="form-control" 
            id="nome" 
            name="nome" 
            placeholder="Digite seu Nome"
            >
    </div>
    <div class="form-group">
        <label for="sobrenome">Sobrenome</label>
        <input 
            type="text" 
            class="form-control" 
            id="sobrenome" 
            name="sobrenome" 
            placeholder="Digite seu Sobrenome"
            >
    </div>
    <div class="form-group">
        <label for="crm">CRM</label>
        <input 
            type="text" 
            class="form-control" 
            id="crm" 
            name="crm" 
            placeholder="Digite seu CRM"
            >
    </div>
    <div class="form-group">
        <label for="data">Data de Nascimento</label>
        <input 
            type="date" 
            class="form-control" 
            id="data" 
            name="data" 
            placeholder="Digite sua Data de Nascimento"
            >
    </div>
    <div class="form-group">
        <label for="senha">Senha</label>
        <input 
            type="password" 
            class="form-control" 
            id="senha" 
            name="senha" 
            placeholder="Digite sua Senha"
            >
    </div>
    <div class="form-group">
        <label for="senha2">Confirme sua senha</label>
        <input 
            type="password" 
            class="form-control" 
            id="senha2" 
            name="senha2" 
            placeholder="Confirme sua Senha"
            >
    </div>
    <button 
    type="submit"
    class="btn btn-primary">Cadastre</button>
    </form>
{% endblock %}
